name : "PODCAST GENERATOR"
description : "Generate a podcast.xml from feeds"
author: "Laxmi"
runs :
  using: "docker"
  image: "Dockerfile"
branding:
  color: "blue"
  icon: "git-branch"
inputs:
   email:
     description: "The commiter`s Email Address"
     required: true
     default: ${{ github.actor }}@localhost
   name:
     description: "The commiter`s username Address"
     required: true
     default: ${{ github.actor }}
      
